# Generated by Django 5.2.4 on 2025-07-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
    ]
