# Generated by Django 5.2.4 on 2025-07-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20250720_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('food', 'Food'), ('clothes', 'Clothes'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('education', 'Education'), ('utilities', 'Utilities'), ('others', 'Others')], max_length=20),
        ),
    ]
