# Generated by Django 5.2.4 on 2025-07-31 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, numbers, spaces, and common symbols allowed.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username can contain letters, numbers, spaces, hyphens, underscores, dots, and @ symbols.', regex='^[a-zA-Z0-9\\s\\-_\\.@]+$')]),
        ),
    ]
