# Generated by Django 5.2.4 on 2025-08-01 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_fix_shared_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensecategory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='incomecategory',
            name='user',
        ),
    ]
