# Generated by Django 5.2.4 on 2025-08-05 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_alter_userprofile_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='no_alphabets', message='Account name must contain at least one letter.', regex='.*[a-zA-Z].*')]),
        ),
    ]
