# Generated by Django 5.2.4 on 2025-07-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='confirmpassword',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
