# Generated by Django 5.2.4 on 2025-07-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_studentdata_confirmpassword_studentdata_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enrollment_no', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=50)),
                ('present', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
