# Generated by Django 5.2.4 on 2025-07-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_facultyattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyattendance',
            name='date',
            field=models.DateField(),
        ),
    ]
