# Generated by Django 5.2.4 on 2025-07-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_facultyattendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('enrollment_no', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('present', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('faculty_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
